name: deployment tutorial

on:
  push:
    branches:
      - master
  pull_request:
    branches: -master

  fork:

jobs:
  my_first_job:
    name: first job
    runs-on: ubuntu-22.04
    steps:
      - name: my_first_step
        run: echo "HELLO WORLD !"
      - name: my_second_step
        run: echo "HELLO BACK !"

  my_second_job:
    name: My second job
    runs-on: ubuntu-22.04
    steps:
      - name: my_first_step
        run: date
      - name: my_second_step
        run: pwd
